package com.rots.entity;
// Generated Nov 5, 2020, 2:30:46 PM by Hibernate Tools 5.4.21.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RotsHourlyMachineDetails generated by hbm2java
 */
@Entity
@Table(name = "rots_hourly_machine_details")
public class RotsHourlyMachineDetails implements java.io.Serializable {

	private Integer id;
	private Integer productId;
	private Integer machineId;
	private Integer status;
	private Integer reasonId;
	private Date startDate;
	private Date endDate;
	private Integer liveProdCount;
	private Integer scrapCount;
	private Integer operatorId;
	private Date createdDate;
	private Integer createdBy;
	private Date updatedDate;
	private Integer updatedBy;

	public RotsHourlyMachineDetails() {
	}

	public RotsHourlyMachineDetails(Integer productId, Integer machineId, Integer status, Integer reasonId,
			Date startDate, Date endDate, Integer liveProdCount, Integer scrapCount, Integer operatorId,
			Date createdDate, Integer createdBy, Date updatedDate, Integer updatedBy) {
		this.productId = productId;
		this.machineId = machineId;
		this.status = status;
		this.reasonId = reasonId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.liveProdCount = liveProdCount;
		this.scrapCount = scrapCount;
		this.operatorId = operatorId;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "product_id", nullable = true)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "machine_id", nullable = true)
	public Integer getMachineId() {
		return this.machineId;
	}

	public void setMachineId(Integer machineId) {
		this.machineId = machineId;
	}

	@Column(name = "status", nullable = true)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "reason_id", nullable = true)
	public Integer getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(Integer reasonId) {
		this.reasonId = reasonId;
	}

	@Column(name = "start_date", nullable = true)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date", nullable = true)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "live_prod_count", nullable = true)
	public Integer getLiveProdCount() {
		return this.liveProdCount;
	}

	public void setLiveProdCount(Integer liveProdCount) {
		this.liveProdCount = liveProdCount;
	}

	@Column(name = "scrap_count", nullable = true)
	public Integer getScrapCount() {
		return this.scrapCount;
	}

	public void setScrapCount(Integer scrapCount) {
		this.scrapCount = scrapCount;
	}

	@Column(name = "operator_id", nullable = true)
	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "created_date", nullable = true)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = true)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_date", nullable = true)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", nullable = true)
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
