package com.rots.entity;
// Generated Nov 5, 2020, 2:30:46 PM by Hibernate Tools 5.4.21.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RotsMachineDataDetails generated by hbm2java
 */
@Entity
@Table(name = "rots_machine_data_test")
public class RotsMachineDataTest implements java.io.Serializable {

	private Integer id;
	private Integer machineId;
	private String productCode;;
	private Integer status;
	private Integer reasonId;
	private Integer liveProdCount;
	private Integer resetCount;
	private Integer shiftId;
	private Integer operatorId;
	private Integer scrapCount;
	private Integer processFlag;
	private Date updatedDate;
	private Date recordDateTime;
	private Date systemDateTime;
	private Date createdDate;
	private Integer createdBy;
	private Integer updatedBy;

	public RotsMachineDataTest() {
	}

	

	public RotsMachineDataTest(int machineId, String productCode, Integer status, Integer reasonId, Integer liveProdCount,
			Integer resetCount, Integer shiftId, Integer operatorId, Integer scrapCount, Integer processFlag,
			Date updatedDate, Date recordDateTime, Date systemDateTime, Date createdDate, Integer createdBy,
			Integer updatedBy) {
		this.machineId = machineId;
		this.productCode = productCode;
		this.status = status;
		this.reasonId = reasonId;
		this.liveProdCount = liveProdCount;
		this.resetCount = resetCount;
		this.shiftId = shiftId;
		this.operatorId = operatorId;
		this.scrapCount = scrapCount;
		this.processFlag = processFlag;
		this.updatedDate = updatedDate;
		this.recordDateTime = recordDateTime;
		this.systemDateTime = systemDateTime;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "machine_id", nullable = true)
	public Integer getMachineId() {
		return this.machineId;
	}

	public void setMachineId(Integer machineId) {
		this.machineId = machineId;
	}

	@Column(name = "product_code")
	public String getProductCode() {
		return productCode;
	}
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	
	@Column(name = "status", nullable = true)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "reason_id", nullable = true)
	public Integer getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(Integer reasonId) {
		this.reasonId = reasonId;
	}

	@Column(name = "live_prod_count", nullable = true)
	public Integer getLiveProdCount() {
		return this.liveProdCount;
	}

	public void setLiveProdCount(Integer liveProdCount) {
		this.liveProdCount = liveProdCount;
	}

	@Column(name = "reset_count", nullable = true)
	public Integer getResetCount() {
		return this.resetCount;
	}

	public void setResetCount(Integer resetCount) {
		this.resetCount = resetCount;
	}

	@Column(name = "shift_id", nullable = true)
	public Integer getShiftId() {
		return this.shiftId;
	}

	public void setShiftId(Integer shiftId) {
		this.shiftId = shiftId;
	}

	@Column(name = "operator_id", nullable = true)
	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	@Column(name = "scrap_count", nullable = true)
	public Integer getScrapCount() {
		return this.scrapCount;
	}

	public void setScrapCount(Integer scrapCount) {
		this.scrapCount = scrapCount;
	}

	@Column(name = "process_flag", nullable = true)
	public Integer getProcessFlag() {
		return this.processFlag;
	}

	public void setProcessFlag(Integer processFlag) {
		this.processFlag = processFlag;
	}


	@Column(name = "record_date_time", nullable = true)
	public Date getRecordDateTime() {
		return this.recordDateTime;
	}

	public void setRecordDateTime(Date recordDateTime) {
		this.recordDateTime = recordDateTime;
	}

	@Column(name = "system_date_time", nullable = true)
	public Date getSystemDateTime() {
		return this.systemDateTime;
	}

	public void setSystemDateTime(Date systemDateTime) {
		this.systemDateTime = systemDateTime;
	}

	@Column(name = "created_date", nullable = true)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = true)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by", nullable = true)
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
	@Column(name = "updated_date", nullable = true)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
