package com.rots.entity;
// Generated Nov 5, 2020, 2:30:46 PM by Hibernate Tools 5.4.21.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RotsShiftMaster generated by hbm2java
 */
@Entity
@Table(name = "rots_shift_master")
public class RotsShiftMaster implements java.io.Serializable {

	private Integer shiftId;
	private String shiftName;
	private Integer shiftNumber;
	private Date startTime;
	private Date endTime;
	private Integer activeFlag;
	private Date createdDate;
	private Integer createdBy;
	private Date updatedDate;
	private Integer updatedBy;

	public RotsShiftMaster() {
	}

	public RotsShiftMaster(Date startTime) {
		this.startTime = startTime;
	}

	public RotsShiftMaster(String shiftName, Date startTime, Date endTime, Date createdDate, Integer createdBy,
			Date updatedDate, Integer updatedBy) {
		this.shiftName = shiftName;
		this.startTime = startTime;
		this.endTime = endTime;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "shift_id", unique = true, nullable = false)
	public Integer getShiftId() {
		return this.shiftId;
	}

	public void setShiftId(Integer shiftId) {
		this.shiftId = shiftId;
	}

	@Column(name = "shift_name", nullable = true)
	public String getShiftName() {
		return this.shiftName;
	}

	
	@Column(name = "shift_number", nullable = false)
	public Integer getShiftNumber() {
		return shiftNumber;
	}

	public void setShiftNumber(Integer shiftNumber) {
		this.shiftNumber = shiftNumber;
	}

	public void setShiftName(String shiftName) {
		this.shiftName = shiftName;
	}

	@Column(name = "start_time", nullable = false)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	
	@Column(name = "end_time", nullable = false)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
	

	@Column(name = "active_flag", nullable = true)
	public Integer getActiveFlag() {
		return activeFlag;
	}
	public void setActiveFlag(Integer activeFlag) {
		this.activeFlag = activeFlag;
	}

	@Column(name = "created_date", nullable = true)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = true)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_date", nullable = true)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", nullable = true)
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
