package com.rots.entity;
// Generated Nov 5, 2020, 2:30:46 PM by Hibernate Tools 5.4.21.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RotsProductMaster generated by hbm2java
 */
@Entity
@Table(name = "rots_product_master")
public class RotsProductMaster {

	private Integer productId;
	private String productName;
	private String productCode;
	private RotsMachineMaster rotsMachineMaster;
	private Integer idealCycleTime;
	private String productYpe;
	private Date createdDate;
	private Integer createdBy;
	private Date updatedDate;
	private Integer updatedBy;
	private Integer activeFlag;

	public RotsProductMaster() {
	}

	

	public RotsProductMaster(String productName, RotsMachineMaster rotsMachineMaster, Integer idealCycleTime, String productYpe,
			Date createdDate, Integer createdBy, Date updatedDate, Integer updatedBy) {
		this.productName = productName;
		this.rotsMachineMaster = rotsMachineMaster;
		this.idealCycleTime = idealCycleTime;
		this.productYpe = productYpe;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "product_name", nullable = true)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "machine_id")
	public RotsMachineMaster getMachineMaster() {
		return this.rotsMachineMaster;
	}

	
	public void setMachineMaster(RotsMachineMaster rotsMachineMaster) {
		this.rotsMachineMaster = rotsMachineMaster;
	}

	@Column(name = "ideal_cycle_time", nullable = true)
	public Integer getIdealCycleTime() {
		return this.idealCycleTime;
	}

	public void setIdealCycleTime(Integer idealCycleTime) {
		this.idealCycleTime = idealCycleTime;
	}

	@Column(name = "product_ype", nullable = true)
	public String getProductYpe() {
		return this.productYpe;
	}

	public void setProductYpe(String productYpe) {
		this.productYpe = productYpe;
	}

	@Column(name = "created_date", nullable = true)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = true)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_date", nullable = true)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", nullable = true)
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "product_code", nullable = false)
	public String getProductCode() {
		return productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "active_flag", nullable = true)
	public Integer getActiveFlag() {
		return activeFlag;
	}
	public void setActiveFlag(Integer activeFlag) {
		this.activeFlag = activeFlag;
	}
	
	

}
