package com.rots.entity;
// Generated Nov 5, 2020, 2:30:46 PM by Hibernate Tools 5.4.21.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RotsMachineMaster generated by hbm2java
 */
@Entity
@Table(name = "rots_machine_master")
public class RotsMachineMaster implements java.io.Serializable {

	private Integer machineId;
	private String machineName;
	private String machineType;
	private Integer totalProducts;
	private Integer activeFlag;
	private Double avgIdealCycleTime;
	private Date createdDate;
	private Integer createdBy;
	private Date updatedDate;
	private Integer updatedBy;

	public RotsMachineMaster() {
	}

	public RotsMachineMaster(String machineName, String machineType, Integer totalProducts, Date createdDate,
			Integer createdBy, Date updatedDate, Integer updatedBy) {
		this.machineName = machineName;
		this.machineType = machineType;
		this.totalProducts = totalProducts;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "machine_id", unique = true, nullable = false)
	public Integer getMachineId() {
		return this.machineId;
	}

	public void setMachineId(Integer machineId) {
		this.machineId = machineId;
	}

	@Column(name = "machine_name", nullable = true)
	public String getMachineName() {
		return this.machineName;
	}

	public void setMachineName(String machineName) {
		this.machineName = machineName;
	}

	@Column(name = "machine_type", nullable = true)
	public String getMachineType() {
		return this.machineType;
	}

	public void setMachineType(String machineType) {
		this.machineType = machineType;
	}

	@Column(name = "total_products", nullable = true)
	public Integer getTotalProducts() {
		return this.totalProducts;
	}

	public void setTotalProducts(Integer totalProducts) {
		this.totalProducts = totalProducts;
	}

	@Column(name = "created_date", nullable = true)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = true)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_date", nullable = true)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", nullable = true)
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
	@Column(name = "active_flag", nullable = true)
	public Integer getActiveFlag() {
		return activeFlag;
	}

	public void setActiveFlag(Integer activeFlag) {
		this.activeFlag = activeFlag;
	}
	
	@Column(name = "avg_ideal_cycle_time", nullable = true)
	public Double getAvgIdealCycleTime() {
		return avgIdealCycleTime;
	}

	public void setAvgIdealCycleTime(Double avgIdealCycleTime) {
		this.avgIdealCycleTime = avgIdealCycleTime;
	}
	
	

}
