package com.rots.entity;
// Generated Nov 5, 2020, 2:30:46 PM by Hibernate Tools 5.4.21.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RotsReasonMaster generated by hbm2java
 */
@Entity
@Table(name = "rots_reason_master")
public class RotsReasonMaster implements java.io.Serializable {

	private Integer id;
	private String reasonTitle;
	private String reasonDesc;
	private Integer reasonType;
	private Integer activeFlag;
	private Date createdDate;
	private Integer createdBy;
	private Date updatedDate;
	private Integer updatedBy;

	public RotsReasonMaster() {
	}

	

	public RotsReasonMaster(String reasonTitle, Date createdDate, Integer createdBy, Date updatedDate, Integer updatedBy) {
		this.reasonTitle = reasonTitle;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@Column(name = "reason_title", nullable = false)
	public String getReasonTitle() {
		return reasonTitle;
	}

	public void setReasonTitle(String reasonTitle) {
		this.reasonTitle = reasonTitle;
	}

	@Column(name = "reason_desc", nullable = true)
	public String getReasonDesc() {
		return reasonDesc;
	}

	public void setReasonDesc(String reasonDesc) {
		this.reasonDesc = reasonDesc;
	}

	@Column(name = "active_flag", nullable = false)
	public Integer getActiveFlag() {
		return activeFlag;
	}

	public void setActiveFlag(Integer activeFlag) {
		this.activeFlag = activeFlag;
	}	

	@Column(name = "created_date", nullable = true)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by", nullable = true)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_date", nullable = true)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", nullable = true)
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}


	@Column(name = "reason_type", nullable = true)
	public Integer getReasonType() {
		return reasonType;
	}
	public void setReasonType(Integer reasonType) {
		this.reasonType = reasonType;
	}
	
	

}
